version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "curtingamedev-livingcalendar"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-nsrpm712p7oe"
s3_prefix = "curtingamedev-livingcalendar"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
