AWSTemplateFormatVersion: 2010-09-09
Description: >-
  livingcalendar-lambda

Transform:
  - AWS::Serverless-2016-10-31

Resources:
  LivingCalendarCGD:
    Type: AWS::Serverless::Function
    Properties:
      Description: This is a lambda that will start up discord bot, post the calendar and die
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: arn:aws:secretsmanager:ap-southeast-2:128153249323:secret:calbo-bCOuYL
      Runtime: nodejs12.x
      Handler: src/handlers/livingcal.scheduledEventLoggerHandler
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
      MemorySize: 128
      Timeout: 100
